name: cbftorch
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch=2.6.0
  - pytorch-cuda=12.4
  - numpy=2.1.3
  - matplotlib=3.9.2
  - pillow=11.0.0
  - pip
  - pip:
    - torchdiffeq==0.2.5
    - cvxopt==1.3.2
    - python-box==7.3.2